# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_738_368_000 # Feb 1, 2025 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.28"
  src = "src"
  test = "tests"
  fs_permissions = [{ access = "read-write", path = "./deployments"}]
libs = ["node_modules", "lib"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  #arbitrum = { key = "${ETHERSCAN_API_KEY}" }
  #avalanche = { key = "${ETHERSCAN_API_KEY}" }
  #goerli = { key = "${ETHERSCAN_API_KEY}" }
  #mainnet = { key = "${ETHERSCAN_API_KEY}" }
  #optimism = { key = "${ETHERSCAN_API_KEY}" }
  sepolia = { key = "${ETHERSCAN_API_KEY}" }
  basesepolia  = { key = "${BASESCAN_API_KEY}" }
  base = { key = "${BASESCAN_API_KEY}" }
  polygon = { key = "${POLYGONSCAN_API_KEY}" }


[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
  avalanche = "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}"
  goerli = "https://goerli.infura.io/v3/${API_KEY_INFURA}"
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
  polygon = "https://polygon-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  basesepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  base = "https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"



